name: Reusable workflow1
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'The person to greet'
        type: string
        required: true
        default: World

jobs:
  reusable-job:
    runs-on: ubuntu-latest
    outputs:
      current-time: ${{ steps.time.outputs.time }}
    steps:
      - name: Greet someone
        run: echo "Hello ${{ github.event.inputs['who-to-greet'] }}"
      - name: Set time
        id: time
        run: echo "time=$(date)" >> $GITHUB_OUTPUT

  another-job:
    runs-on: ubuntu-latest
    steps:
      - name: another echo
        run: echo "another line"

  depending-job:
    needs: [reusable-job, another-job]
    runs-on: ubuntu-latest
    steps:
      - name: another echo
        run: echo "another line"
